version: '3.9'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frontend
    restart: unless-stopped
    ports:
      - "3003:3003"
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  node_modules:
